### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by vaheqelyan** [rollup/rollup#1407]
I have an issue in the console.

```code
master.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at master.js:1
    at master.js:1
    at master.js:1
```

I faced the same problem before when I imported other modules, such as mobx,mobx-react,redux...

Here is my code

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import reactMotion from 'react-motion';
const { Spring } = reactMotion;

const app = document.getElementById('container');


class App extends React.Component {
  render() {
    return(
      <Spring defaultValue={0} endValue={360}>
        {val => {
          let style={
            width:val,
            height:val,
            position:'absolute',
            top:val*0.25,
            left:val*0.25,
            border:"1px sold",
            transform:`rotate(${val}deg)`
          }
          return <div style={style}>{val}></div>
        }}
      </Spring>
    )
  }
}

ReactDOM.render(<App/>,app);
```

Here is my config file.

```js
import fs from 'fs';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import bundleSize from 'rollup-plugin-bundle-size';
import uglify from 'rollup-plugin-uglify';
import replace from 'rollup-plugin-replace';
import json from 'rollup-plugin-json';

import path from 'path';

export default {
  entry: path.join('public', 'components', 'master.js'),
  dest: path.join('public', 'build', 'master.js'),
  format: 'umd',
  external:['react-motion'],
  plugins: [
    json(),
    bundleSize(),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js', '.jsx']
    }),
    commonjs({
      include: 'node_modules/**'
    }),
    babel({
      exclude: 'node_modules/**'
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    }),
    uglify()
  ],
  sourceMap: true,
};

```

what is the problem?

**Comment by olsonpm** [comment]
You are likely encountering an [optional dependency](https://github.com/rollup/rollup/issues/1385), but to find out for sure please create a github repo that reproduces your issue.

**Comment by atompkins** [comment]
repro here https://github.com/atompkins/repro

**Comment by lukastaegert** [comment]
#2344 should fix this issue for good, please check it out. Hope we can release it soon.

**Comment by bietkul** [comment]
@Rich-Harris I'm still getting this error.
Here is the codesandbox example
https://codesandbox.io/s/vue-template-29pee
Rollup config
https://github.com/appbaseio/reactivesearch/blob/next/packages/vue/rollup.config.js

**Comment by davinderpalrehal** [comment]
@lukastaegert and @Rich-Harris getting the same error with Rollup 2.3.2

`Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined`

**Comment by lukastaegert** [comment]
As the original issue is resolved, you might want to create a reproduction and open a new issue?

**Comment by asmyshlyaev177** [comment]
Same problem, seems to me that rollup has much more issues then webpack.

**Comment by lukastaegert** [comment]
https://github.com/rollup/rollup/issues/1407#issuecomment-609014780

**Comment by dengnan123** [comment]
Same problem
```
 "rollup": "1.27.8"
```

**Comment by lukastaegert** [comment]
We are currently at 2.22.2
