### ISSUE TITLE
npm script: rollup config fail

### ISSUE THREAD

**Issue by dalisoft** [rollup/rollup#1647]
I am using rollup over 6month on all my projects.
I'm like this script: `npm run source` (does `rollup -c`), but it fails.

Directly: `rollup -c` works best without any issues

Here log
```bash
D:\GitHub\es6-tween>npm run source

> es6-tween@3.8.20 source D:\GitHub\es6-tween
> rollup -c

?   You must specify an --input (-i) option

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es6-tween@3.8.20 source: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6-tween@3.8.20 source script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dalerjon\AppData\Roaming\npm-cache\_logs\2017-09-23T17_01_
51_436Z-debug.log
```

**Comment by Arcath** [comment]
This started happening to me randomly.

`rollup -c` works fine. Ask `grunt-shell` or npm scripts to run it and it fails. I even tried adding the absolute path to `rollup.config.js` to the command in my gruntfile and nothing.

NPM: 5.0.0
Node: 8.0.0
Rollup: 0.51.8
Grunt: 1.0.1

**Comment by dalisoft** [comment]
This happened me, delete package.lock, yarn.lock and other package manager lockfile, update deps then generate lockfile. Issue was fixed

**Comment by Arcath** [comment]
I've done that and I'm still getting the same error.

**Comment by jsnelgro** [comment]
@dalisoft I'm also still encountering this issue after trying your solution. Any other ideas?

**Comment by jsnelgro** [comment]
Spoke too soon! @Arcath make sure you're not using a globally installed version of rollup. i.e. run `npm install --save-dev rollup` in your project.
