### ISSUE TITLE
Mark dependency as internal?

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup#1906]
I'm not sure how am I supposed to repro this with the REPL... I hope it's okay this way, I think it's mostly a documentation issue?

I have a code that imports a dependency, I'd like the final bundle to include such dependency instead of reference to it.

So:

    import lodash from 'lodash';
    
    // use lodash somehow

Should output:

    /** all the Lodash source code here **/
    
    // use lodash somehow

How can I do this?

**Comment by mrkishi** [comment]
You're probably looking for [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve), which lets you import modules from `node_modules` (ie. installed by npm/yarn), and [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs), which lets you import CommonJS modules (most npm packages are in this format).

For `lodash` specifically, you can skip `rollup-plugin-commonjs` and import `lodash-es` instead.

**Comment by FezVrasta** [comment]
Thanks, I was aware of those plugins but I didn't thought that they were required to make the dependency being treated as internal.

It makes sense because without them Rollup can't know how to import/parse them, but it's quite unclear why it shouldn't just throw an error instead of fallback to treat them as external.

Some kind of documentation to explain this behavior seems much needed, if not directly a better error message/warning in the tool.

**Comment by mrkishi** [comment]
Well, it has no way to know it's an error, since it's a valid use-case.

It's also pretty [well documented](https://rollupjs.org/guide/en#npm-packages) in my opinion, but feel free to point out improvements.

**Comment by FezVrasta** [comment]
Since Rollup already shows a warning telling that the dependency has no name, it could also show a warning telling that it is being treated as external because there's not a proper plugin to import them, with an option to disable the warning maybe.

**Comment by ashleyw** [comment]
I published a plugin which allows you to explicitly mark a dependency as internal. I use it after [rollup-plugin-auto-external](https://www.npmjs.com/package/rollup-plugin-auto-external), which marks all dependencies in your package.json as external, to explicitly bundle certain key dependencies.

https://www.npmjs.com/package/rollup-plugin-internal

**Comment by kettanaito** [comment]
In case you'd like for Rollup to throw an error when an internal dependency is not resolved, I can suggest you to leverage the `onwarn` hook and check for your dependency there:

```js
const rollupConfig = {
  onwarn(message) {
    if (message.code === 'UNRESOLVED_IMPORT' && message.source === 'lodash') {
      throw new Error(`Could not resolved "lodash" module`)
    }
  }
}
```

This will result into the error being thrown instead of the warning.
