### ISSUE TITLE
Code is lost when assigning to object at runtime

### ISSUE THREAD

**Issue by danmarshall** [rollup/rollup#2306]
Hello, thanks for Rollup, it is super fast. I came a cross an issue when using object maps. I like to use this pattern where I use a "well known" key:

```js
const keys = {
    KEY_A: 'a',
    KEY_B: 'b'
}

const map = {};

map[keys.KEY_A] = function (x) {
    console.log('a called with ' + x);
};

map[keys.KEY_B] = function (x) {
    console.log('b called with ' + x)
};

function callMap(key, x) {
    const fn = map[key];
    if (fn) {
        fn(x);
    }
    else {
        console.log('key does not exist: ' + key);
    }
}

callMap('a', 0);
callMap('z', 0);
callMap('b', 0);
```
In the Repl, you can see that code gets lost:
```js
(function () {
    'use strict';

    function callMap(key, x) {
        {
            console.log('key does not exist: ' + key);
        }
    }

    callMap('a', 0);
    callMap('z', 0);
    callMap('b', 0);

}());
```

**Comment by guybedford** [comment]
I added your code sample to the REPL here - 

https://rollupjs.org/repl?version=0.60.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwa2V5cyUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBLRVlfQSUzQSUyMCdhJyUyQyU1Q24lMjAlMjAlMjAlMjBLRVlfQiUzQSUyMCdiJyU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwbWFwJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25tYXAlNUJrZXlzLktFWV9BJTVEJTIwJTNEJTIwZnVuY3Rpb24lMjAoeCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2ElMjBjYWxsZWQlMjB3aXRoJTIwJyUyMCUyQiUyMHgpJTNCJTVDbiU3RCUzQiU1Q24lNUNubWFwJTVCa2V5cy5LRVlfQiU1RCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCdiJTIwY2FsbGVkJTIwd2l0aCUyMCclMjAlMkIlMjB4KSU1Q24lN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwY2FsbE1hcChrZXklMkMlMjB4KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMGZuJTIwJTNEJTIwbWFwJTVCa2V5JTVEJTNCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKGZuKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBmbih4KSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwZWxzZSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygna2V5JTIwZG9lcyUyMG5vdCUyMGV4aXN0JTNBJTIwJyUyMCUyQiUyMGtleSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuY2FsbE1hcCgnYSclMkMlMjAwKSUzQiU1Q25jYWxsTWFwKCd6JyUyQyUyMDApJTNCJTVDbmNhbGxNYXAoJ2InJTJDJTIwMCklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

But it doesn't seem to be removing the code as in your example? Can you perhaps share a direct repl link?

**Comment by danmarshall** [comment]
Hi Guy - I am getting inconsistent results from the Repl. Which could be a separate issue. I clicked your link 10 times (open in a new tab). 7/10 times my issue does not appear, 3/10 times I see the issue. Would you mind testing your link several times?

**Comment by guybedford** [comment]
Very odd, it is working consistently for me here. Could it not be a rendering issue on the repl perhaps? If you click through the different formats on the right does it correct in the invalid cases?

**Comment by danmarshall** [comment]
Clicking through the formats does fix the issue. Seems like the Repl is not perfectly consistent with the results locally - I've created a repo which reproduces the error:

https://github.com/danmarshall/rollup-map

**Comment by guybedford** [comment]
Ahh, it seems the REPL is still running the older Rollup release.

The REPL on 0.62.0 definitely gives the issue - 

https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwa2V5cyUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBLRVlfQSUzQSUyMCdhJyUyQyU1Q24lMjAlMjAlMjAlMjBLRVlfQiUzQSUyMCdiJyU1Q24lN0QlNUNuY29uc3QlMjByZXN1bHRzJTIwJTNEJTIwJTVCJTVEJTNCJTVDbmNvbnN0JTIwbWFwJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25tYXAlNUJrZXlzLktFWV9BJTVEJTIwJTNEJTIwZnVuY3Rpb24lMjAoeCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmVzdWx0cy5wdXNoKCdhJTIwY2FsbGVkJTIwd2l0aCUyMCclMjAlMkIlMjB4KSUzQiU1Q24lN0QlM0IlNUNuJTVDbm1hcCU1QmtleXMuS0VZX0IlNUQlMjAlM0QlMjBmdW5jdGlvbiUyMCh4KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXN1bHRzLnB1c2goJ2IlMjBjYWxsZWQlMjB3aXRoJTIwJyUyMCUyQiUyMHgpJTVDbiU3RCUzQiU1Q24lNUNuZnVuY3Rpb24lMjBjYWxsTWFwKGtleSUyQyUyMHgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwZm4lMjAlM0QlMjBtYXAlNUJrZXklNUQlM0IlNUNuJTIwJTIwJTIwJTIwaWYlMjAoZm4pJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGZuKHgpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjBlbHNlJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJlc3VsdHMucHVzaCgna2V5JTIwZG9lcyUyMG5vdCUyMGV4aXN0JTNBJTIwJyUyMCUyQiUyMGtleSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuY2FsbE1hcCgnYSclMkMlMjAwKSUzQiU1Q25jYWxsTWFwKCd6JyUyQyUyMDApJTNCJTVDbmNhbGxNYXAoJ2InJTJDJTIwMCklM0IlNUNuJTVDbmNvbnNvbGUubG9nKHJlc3VsdHMuam9pbignJTVDJTVDbicpKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by danmarshall** [comment]
Good catch @guybedford ! I didn't see the version option 👍

**Comment by lukastaegert** [comment]
Just a heads up: Besides this one, there are currently some other related issues due to some recent changes in the tree-shaking algorithm. I am working on fix for all of them but it will involve some changes in the way we handle deoptimizations. More about this shortly.

**Comment by lukastaegert** [comment]
Fix at #2315

**Comment by lukastaegert** [comment]
Fix released via Rollup v0.63.0, thanks for being patient!

**Comment by danmarshall** [comment]
Thanks!!

But... it appears the problem still exists, albeit to a lesser degree: [link to repl](https://rollupjs.org/repl?version=0.63.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwa2V5cyUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBLRVlfQSUzQSUyMCdhJyUyQyU1Q24lMjAlMjAlMjAlMjBLRVlfQiUzQSUyMCdiJyU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwbWFwJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25tYXAlNUJrZXlzLktFWV9BJTVEJTIwJTNEJTIwZnVuY3Rpb24lMjAoeCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2ElMjBjYWxsZWQlMjB3aXRoJTIwJyUyMCUyQiUyMHgpJTNCJTVDbiU3RCUzQiU1Q24lNUNubWFwJTVCa2V5cy5LRVlfQiU1RCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCdiJTIwY2FsbGVkJTIwd2l0aCUyMCclMjAlMkIlMjB4KSU1Q24lN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwY2FsbE1hcChrZXklMkMlMjB4KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMGZuJTIwJTNEJTIwbWFwJTVCa2V5JTVEJTNCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKGZuKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBmbih4KSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwZWxzZSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygna2V5JTIwZG9lcyUyMG5vdCUyMGV4aXN0JTNBJTIwJyUyMCUyQiUyMGtleSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuY2FsbE1hcCgnYSclMkMlMjAwKSUzQiU1Q25jYWxsTWFwKCd6JyUyQyUyMDApJTNCJTVDbmNhbGxNYXAoJ2InJTJDJTIwMCklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

this piece of code is still missing:
```js
map[keys.KEY_B] = function (x) {
    console.log('b called with ' + x)
};
```

**Comment by lukastaegert** [comment]
According to the REPL, the code is only missing in 0.62.0 but in 0.63.0, everything is in place. Could you please check again?

**Comment by derrickb** [comment]
@lukastaegert I am also experiencing small pieces of code being stripped out after 0.61.0, and unfortunately have been unable to reproduce it on the REPL.

```
const isWindows = window.navigator.platform.indexOf("Win") >= 0;

const myObject = {
  init() {
    if (!isWindows) {
      console.log('not windows');
    }
  }
}
```
The `if` block will be stripped even though myObject.init() is called inside `window.onload` in another module.  This is an extremely simplified example but captures what I'm seeing.

**Comment by lukastaegert** [comment]
A few things you might try that could help shed some light on this:

If the if-statement is stripped even though the object is included then rollup *probably*  thinks that `isWindows` is undefined. If you place the if-statement directly below the definition of `isWindows`, is it stripped or retained?

Is the definition of `isWindows` and its usage in the same file? If not, how is the variable passed on?

If you comment out all other usages of `isWindows`, does this changes anything or are there no other usages?

**Comment by danmarshall** [comment]
Ok, my example seems to be working now 👍 must have been caching?
Anyways, thanks a lot! 🥇

**Comment by lukastaegert** [comment]
Thanks for the heads-up, that is good to know!

**Comment by derrickb** [comment]
@lukastaegert thank you for the replies! Here is a bit more info that's reflective of my actual code, and some answers to your questions:

>  If you place the if-statement directly below the definition of isWindows, is it stripped or retained?

Retained

> Is the definition of isWindows and its usage in the same file? If not, how is the variable passed on?

Yes all in the same file, see my example below

> If you comment out all other usages of isWindows, does this changes anything or are there no other usages?

No other usages

Here is a more detailed example. Still heavily simplified but structurally this reflects my code. There are **two** if blocks that are getting stripped, that **weren't in 0.60.7**. I've marked these with comments:
```
export { theme as default };

const isWindows = window.navigator.platform.indexOf("Win") >= 0;

const theme = {
  init() {
    this.styleSheet = document.styleSheets[document.styleSheets.length - 1];

    if (!isWindows) { //STRIPPED
      addRule('::-webkit-scrollbar', 'width: 13px;');
    }
  }
}

// this function is retained because it is called elsewhere in the module
function addRule(selector, rule) {
  if (theme.styleSheet) { //STRIPPED
    sheet.addRule(selector, rule);
  }
}
```
My built file is 3k lines long, with many objects and modules using similar init functions, conditionals, etc. Yet these are the only two blocks that are being stripped. If there's anything else I should try, please let me know!

**Comment by derrickb** [comment]
I am close to a repro on the REPL for this. The confusing thing is that in my actual code, `getAsset` is definitely defined and included in my output. The only way to reproduce the stripped segments was to comment out the function on the REPL. So... you're now seeing the stripping properly, it's just weird that it works on the REPL if `getAsset` is undefined, as where in my code it's stripped despite it being defined.

https://rollupjs.org/repl?version=0.63.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHRoZW1lJTIwZnJvbSUyMCcuJTJGdGhlbWUuanMnJTNCJTVDbiU1Q250aGVtZS5pbml0KCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydGhlbWUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwdGhlbWUlMjBhcyUyMGRlZmF1bHQlMjAlN0QlM0IlNUNuJTVDbmNvbnN0JTIwaXNXaW5kb3dzJTIwJTNEJTIwd2luZG93Lm5hdmlnYXRvci5wbGF0Zm9ybS5pbmRleE9mKCU1QyUyMldpbiU1QyUyMiklMjAlM0UlM0QlMjAwJTNCJTVDbmlmJTIwKCFpc1dpbmRvd3MpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdub3QlMjBzdHJpcHBlZCcpJTNCJTVDbiU3RCU1Q24lNUNuY29uc3QlMjB0aGVtZSUyMCUzRCUyMCU3QiU1Q24lMjAlMjBpbml0KCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGhpcy5zdHlsZVNoZWV0JTIwJTNEJTIwZG9jdW1lbnQuc3R5bGVTaGVldHMlNUJkb2N1bWVudC5zdHlsZVNoZWV0cy5sZW5ndGglMjAtJTIwMSU1RCUzQiU1Q24lNUNuJTIwJTIwJTIwJTIwaWYlMjAoIWlzV2luZG93cyklMjAlN0IlMjAlMkYlMkZTVFJJUFBFRCU1Q24lMjAlMjAlMjAlMjAlMjAlMjBhZGRSdWxlKCclM0ElM0Etd2Via2l0LXNjcm9sbGJhciclMkMlMjAnd2lkdGglM0ElMjAxM3B4JTNCJyklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q3QlNUN0JTVDbiU1Q3QlNUN0c29tZUZ1bmMoKSUzQiU1Q24lMjAlMjAlN0QlMkMlNUNuJTVDdCU1Q24lNUN0JTJGJTJGZ2V0QXNzZXQoKSUyMCU3QiU3RCU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwYWRkUnVsZShzZWxlY3RvciUyQyUyMHJ1bGUpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKHRoZW1lLnN0eWxlU2hlZXQpJTIwJTdCJTIwJTJGJTJGU1RSSVBQRUQlNUNuJTIwJTIwJTIwJTIwc2hlZXQuYWRkUnVsZShzZWxlY3RvciUyQyUyMHJ1bGUpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwc29tZUZ1bmMoKSUyMCU3QiU1Q24lNUN0YWRkUnVsZSgnc29tZVJ1bGUnJTJDJTIwJTYwYmFja2dyb3VuZC1pbWFnZSUzQSUyMHVybCglMjQlN0J0aGVtZS5nZXRBc3NldCgnYXJyb3ctdXAnKSU3RCklM0IlNjApJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by lukastaegert** [comment]
Thanks, now I know what is going on! This one is important but it is going to be tricky to fix. The problem is that you are adding the `styleSheet` variable to `theme` by adding it to `this` instead of the `theme` variable which you could do here as well.

But this modification is not properly associated with the underlying object by the algorithm so rollup still thinks that `init` (and possibly `getAsset`) are the only keys to be found in `theme`. Thus it thinks that `theme.styleSheet` is `undefined` and removes the if statement.

The reason `getAsset` is removed is because calling it does not have a side-effect. If you remove the definition then calling it has the side-effect of throwing an error so the call is retained :)

We will have to think about how to properly track modifications of `this` as the value of `this` depends entirely on how the method is called but we will get there. But it may take some time. Until then, you can adjust your code to not use `this` to modify objects outside of classes. in classes or basically objects created via a constructor, usage of `this` should be entirely safe, though.

**Comment by lukastaegert** [comment]
Created #2345 to track

**Comment by derrickb** [comment]
Thank you!! Changing this.styleSheet to theme.styleSheet prevented the stripping, all is working now and i can safely update rollup for my project.
I definitely should have rewritten this but I had it as a class at one point and then changed it to an object literal and it kept working so I put it on the backburner. Good catch!

**Comment by lukastaegert** [comment]
Well, your code was correct nonetheless. I'm sure we'll figure out a way to track this properly soon!
