### ISSUE TITLE
displayName is incorrect for exported module

### ISSUE THREAD

**Issue by lifeiscontent** [rollup/rollup#2514]
- Rollup Version: 0.66.6
- Operating System (or Browser): OSX 10.14
- Node Version: 8.12.0

### How Do We Reproduce?

https://rollupjs.org/repl?version=0.66.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMGN1YmUlMjBhcyUyMGRlZmF1bHRDdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbiU1Q25jb25zdCUyMGN1YmUlMjAlM0QlMjAoLi4uYXJncyklMjAlM0QlM0UlMjBkZWZhdWx0Q3ViZSguLi5hcmdzKSUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwY3ViZSUyMCU3RCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBtYXRocy5qcyU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwaXNuJ3QlMjB1c2VkJTIwYW55d2hlcmUlMkMlMjBzbyU1Q24lMkYlMkYlMjBSb2xsdXAlMjBleGNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTNCJTVDbiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

the main named export gets renamed to cube$1 which breaks `cube$1.displayName`
the `import {cube as cubeDefault} from './maths.js'` should be named cubeDefault

### Actual Behavior

the main named export is named `cube$1`
the import statement is transformed back to `cube`

**Comment by objectkit** [comment]
It is not appropriate to change source code to suit a build tool when the build tool is in [breach of a standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)

@def0x099, my statement above is not aimed at you and I see the value of your solution as a JIT fix.

I for one do have a need to know if the "$ solution" is a "forever solution", so I posted an open question on Gitter about this to avoid a slow Q&A cycle that circumvents admission of the problem by fatiguing the question. 

Of course, a group of people talking together in person or by video call would be much better, but I felt the need to at least invite the potential for fix. 

Peace.

**Comment by shellscape** [comment]
Just checked the REPL link and it looks like this has been fixed in recent versions.

**Comment by lifeiscontent** [comment]
@shellscape you're wrong it's still broken.

**Comment by lifeiscontent** [comment]
@shellscape can you please reopen this issue. It is still broken.
