### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by btakita** [rollup/rollup#883]
I periodically get the following error after `rollup --watch` rebuilds  after a while. I'm not able to provide a confident estimate on the number of times, but it does not seem to happen shortly after I restart the watch process.

```
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x17b8880c9e31 <JS Object>
    1: Join(aka Join) [native array.js:160] [pc=0x1319899a837f] (this=0x17b888004189 <undefined>,w=0x3ec35a21fe39 <JS Array[250]>,x=250,N=0x17b8880042e1 <String[0]: >,M=0x17b8880b49e9 <JS Function ConvertToString (SharedFunctionInfo 0x17b88804ef79)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:~343] [pc=0x131984b4aeec] (this=0x17b888004189 <undefined>,N=0x17b8880042e1 <String[0]:...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0xfb7bfc [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x13198340961b
./bin/browser-rollup-watch.sh: line 4: 27781 Aborted                 rollup -c "companies/browser.rollup.config.js" --watch
```

companies/browser.rollup.config.js

```
var new__browser__config__rollup = require("ctx-core/rollup/lib").new__browser__config__rollup;
module.exports = new__browser__config__rollup({
  entry: "companies/browser.js",
  dest: "public/dist/companies.js",
  sourceMap: true
});
```

ctx-core/rollup/lib.js

``` js
var riot__rollup = require('rollup-plugin-riot')
  , node_resolve__rollup = require('rollup-plugin-node-resolve')
  , includepaths__rollup = require('rollup-plugin-includepaths')
  , commonjs__rollup = require('rollup-plugin-commonjs')
  , sourcemaps__rollup = require('rollup-plugin-sourcemaps')
  , alias__rollup = require('rollup-plugin-alias')
  , json__rollup = require('rollup-plugin-json')
  , watch__rollup = require('rollup-watch')
  , babel__rollup = require('rollup-plugin-babel')
module.exports = {
  new__config__rollup,
  new__browser__config__rollup,
  new__node__config__rollup
}
function new__browser__config__rollup() {
  return new__config__rollup.call(this, {
    intro: `
      var global = typeof window !== 'undefined' ? window :
        typeof global !== 'undefined' ? global :
        this`,
    format: 'iife',
    globals: {
      global: 'window',
      riot: 'riot',
      d3: 'd3'
    },
    plugins: [
      alias__rollup({
        'js-console-color': 'ctx-core/logger/browser.js'
      }),
      sourcemaps__rollup(),
      riot__rollup(),
      includepaths__rollup({
        include: {},
        paths: ['.', './ctx-core', './node_modules'],
        external: [],
        extensions: ['.js', '.json', '.html', '.tag']
      }),
      node_resolve__rollup({
        jsnext: true,
        main: true,
        browser: true
      }),
      commonjs__rollup({
        include: 'node_modules/**',
        extensions: [ '.js', '.coffee' ]
      }),
      json__rollup(),
      babel__rollup({
        exclude: 'node_modules/**'
      })
    ]
  }, ...arguments)
}
function new__node__config__rollup() {
  return new__config__rollup.call(this, {
    format: 'cjs',
    plugins: [
      riot__rollup(),
      includepaths__rollup({
        include: {},
        paths: ['./', './ctx-core', './node_modules'],
        external: [
          'aws-sdk',
          'co-fs',
          'crypto',
          'debug',
          'fs',
          'glob',
          'iconv-lite',
          'inflation',
          'inquirer',
          'inquirer-autocomplete-prompt',
          'isomorphic-fetch',
          'koa',
          'koa-generic-session',
          'koa-redirects',
          'koa-sslify',
          'koa-static',
          'methods',
          'mime-db',
          'os-shim',
          'parseurl',
          'path',
          'pg',
          'pg-native',
          'shelljs',
          'statuses',
          'temp',
          'throng',
          'try-thread-sleep',
          'vorpal'
        ],
        extensions: ['.js', '.json', '.html', '.tag']
      }),
      node_resolve__rollup({
        jsnext: true,
        main: true,
        preferBuiltins: true
      }),
      commonjs__rollup({
        include: 'node_modules/**',
        extensions: [ '.js', '.coffee' ]
      }),
      babel__rollup({
        exclude: 'node_modules/**'
      })
    ]
  }, ...arguments)
}
function new__config__rollup() {
  return Object.assign({
    external: ['riot', 'fs', 'path', 'process']
  }, ...arguments)
}
```

**Comment by btakita** [comment]
I left an unused `require("rollup-watch")` in `ctx-core/rollup/lib.js`. I'll try removing it & see if the issue happens.

**Comment by snuggs** [comment]
@btakita still getting my feet wet with contributing to rollup (et. al). @Victorystick @TrySound Brian is actually someone who I work with at my day job. Have been evangelizing rollup and this "bug" currently has our Slack channel on 🔥  any help would be appreciated.

As an aside perhaps this issue is more related to `rollup-watch` than `rollup` @btakita @Victorystick @TrySound? https://github.com/rollup/rollup-watch

**Comment by TrySound** [comment]
@snuggs Can you try this branch instead. Maybe chokidar can fix this issue.
https://github.com/rollup/rollup-watch/pull/16

**Comment by snuggs** [comment]
@TrySound thanks brah! 🙏  Should we file an issue with https://github.com/paulmillr/chokidar? If you had a hunch where would you expect it's failing?  /cc @btakita ^^^

**Comment by Rich-Harris** [comment]
rollup-watch doesn't currently use chokidar, it uses `fs.watch` directly (I've had bad experiences with every single file watcher and I wanted to see if we could get away with just using what comes with Node – apparently the answer is 'no you can't'). If you run

```bash
npm install -D bdougherty/rollup-watch#fix-infinite-loop
``` 

you should be able to see if https://github.com/rollup/rollup-watch/pull/16 fixes the issue. Let us know!

**Comment by bdougherty** [comment]
@Rich-Harris I haven't been able to look into it further, but when I install it directly from my branch I get an error claiming it's not installed:

`rollup --watch depends on the rollup-watch package, which could not be found. You can install it globally (recommended) with npm install -g rollup-watch`

It works if I use `npm link` though.

**Comment by btakita** [comment]
Now `rollup --watch` no longer watches. It seems to be a regression with rollup 0.34.11. Does not happen with rollup 0.34.10.

**Comment by Rich-Harris** [comment]
@btakita sorry about that – fixed in 0.34.12 (see #887).

@bdougherty are you running `rollup` directly on the command line? That might explain why it can't find a local copy of `rollup-watch` – if you install it locally (`npm i -D rollup`) and run it via an npm script...

```js
// package.json
{
  ...
  "scripts": {
    "build": "rollup -c"
  }
}
```

...or like so...

```bash
node_modules/.bin/rollup -c -w
```

...it might let you use the chokidar fork.

**Comment by snuggs** [comment]
@btakita I told ya this team is so uffin' RAD /cc @Rich-Harris @TrySound 

![](https://media.giphy.com/media/tLnRdhVE4WQco/giphy.gif)

**Comment by btakita** [comment]
@snuggs true. i'm enjoying using rollup.

though, i'm still having an issue with `--watch`. it seems like watch only rebundles one time, then the watched files are ignored.

i used .sh scripts to manage multiple rollup bundles.

https://github.com/ctx-core/ctx-core/tree/master/rollup

https://github.com/ctx-core/ctx-core/blob/master/rollup/browser-rollup-watch.sh
https://github.com/ctx-core/ctx-core/blob/master/rollup/http-rollup-watch.sh
https://github.com/ctx-core/ctx-core/blob/master/rollup/rollup-files.js

**Comment by snuggs** [comment]
@bdougherty @TrySound @Rich-Harris ^^^ Any context would really help out our team. Can also contribute if point in the right direction.

Have been using browserify as a crutch in the meantime.

![](ttps://media.giphy.com/media/11nQ2iZnQpPkgo/giphy.gif)

**Comment by ntilwalli** [comment]
I just encountered this same problem.  After the first two rebundles after saving, the watcher continually rebundles until it crashes like shown in the OP's message.

```
Security context: 0x186b6e9e3ac1 <JS Object>
    1: decode(aka decode) [/usr/local/lib/node_modules/rollup/dist/rollup.js:~302] [pc=0x2b1637decc2b] (this=0x186b6e904189 <undefined>,mappings=0xe400f804101 <Very long string[2212379]>)
    2: render [/usr/local/lib/node_modules/rollup/dist/rollup.js:9057] [pc=0x2b1638411dc3] (this=0xad7b6073c81 <a Bundle with map 0x17f96d511939>,options=0x3f6fe25f9359 <an Object with map 0x17ae602dec09>)
   ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

**Comment by BKcore** [comment]
Same issue here on `"rollup": "0.36.3", rollup-watch": "2.5.0"`. Any progress on this?

**Comment by ahelmberger** [comment]
We have the same problem using gulp watch. It seems to be a memory leak when re-using a cache object for a longer time. Serializing and deserializing the cache object seems to fix the problem:

~~~
let cache = null;

rollup({
  entry: 'main.js',
  cache: JSON.parse(cache)
})
.then(bundle => {
  cache = JSON.stringify(bundle);
  return bundle.write({
    dest: 'bundle.js'
  });
});
~~~

Note the `JSON.stringify` and `JSON.parse`.

**Comment by AngusFu** [comment]
Still got into crazy endless loop with rollup 0.36.3 and rollup-watch 2.5.0... Just repeat pressing `ctrl + s` serveral times in 1s...

**Comment by Rich-Harris** [comment]
It's *possible* that this issue was fixed by https://github.com/rollup/rollup/pull/1205. If anyone is still experiencing this issue, any chance you could try out the latest version, and if this is still a live issue provide a repro? Thanks

**Comment by cfebs** [comment]
I was able to repro with 0.41.4 on linux. We use rollup with a custom chokidar script, essentially just running `rollup.rollup` again.

The bundle process is pretty standard and uses a shared cache var.

With cache var our builds are about 2-3s on average.

Running a loop that `touch`s a module in the project every 6s, memory usage slowly creeps upwards.

Finally at around the 35th `touch` we get the same fatal reported in the ticket.

The first bundle `process.memoryUsage()`: `{ rss: 593084416, heapTotal: 563167232, heapUsed: 510649792 }`

and here's the one right before it dies: `{ rss: 1497608192, heapTotal: 1460498432, heapUsed: 1309417768 }`

For reference we are watching about 102 source modules.

#### Trying without cache
Same test constraints, just removing the cache variable.

Starts at around: `{ rss: 325095424, heapTotal: 299114496, heapUsed: 255929400 }`

Dies at around: it doesn't die! But it's much slower, 7s average build.

Memory usage fluctuates quite a bit.

#### Notes

Here are the memory usage logs over time for both tests: https://gist.github.com/cfebs/15d095b3848ebcfec283e80502d1e44a

**Comment by grapemix** [comment]
i had the same problem too. i fixed it after upgrading to 0.41.6 and ionic app-script 1.3.1. Hope helps.

**Comment by veltman** [comment]
Just a note that I still see this issue with 0.41.6 - @ahelmberger's serialize/deserialize solution seems to fix it, but roughly doubles the incremental bundling time.

**Comment by snuggs** [comment]
@Rich-Harris *FINALLY*!!!! 

Party time! 🎉 🎉 

@btakita 

https://user-images.githubusercontent.com/1162160/27997975-71697bd0-64d1-11e7-809e-924a231fc3f2.gif

**Comment by Rich-Harris** [comment]
@snuggs I know right! All thanks to @dmitrage. Released as 0.43.1

**Comment by Tzook** [comment]
@Rich-Harris This is still happening to me, using 0.45.2.
After starting to use the "cache" option, the out of memory crashes began.
I saw this issue and upgraded Rollup from 0.41.4 to 0.45.2 (latest) in order to fix it.
The fatal still happens and crashes.

**Comment by sandorfr** [comment]
I ran into the same kind of issue recently. There is one way to workaround the issue : Increase node max heap size. I found that the node utility [increase-memory-limit](https://github.com/endel/increase-memory-limit) was a handy way to do so.

**Comment by Havunen** [comment]
We are seeing this same error on our team city agents. We recently switched huge application build process to rollup. Which is working great, output is 1MB less than using Webpack!! 👍 . This exception is however breaking the build randomly. 

Our agents use Windows Server and nodeJS v6.11.3
this is our rollup conf
```javascript
module.exports = {
    input: path.join(__dirname, 'src/main.js'),
    name: 'XXX',
    plugins: [
        alias({
            'inferno-component': path.resolve(__dirname, 'node_modules/inferno-component/dist/index.es.js'),
            'inferno-shared': path.resolve(__dirname, 'node_modules/inferno-shared/dist/index.es.js'),
            inferno: path.resolve(__dirname, 'node_modules/inferno/dist/index.es.js'),
            keymirror: path.resolve(__dirname, 'src/js/utils/keymirror.js')
        }),
        json({
            // All JSON files will be parsed by default,
            // but you can also specifically include/exclude files
            include: 'node_modules/**',  // Default: undefined
            preferConst: false // Default: false
        }),
        nodeResolvePlugin({
            jsnext: false,  // Default: false
            main: true,  // Default: true
            browser: true,  // Default: false
            preferBuiltins: false,
            extensions: ['.js']
        }),
        commonjsPlugin({
            sourceMap: isDeploy,
            include: ['node_modules/**'],
            extensions: ['.js']
        }),
        babelPlugin({
            babelrc: false,
            sourceMaps: isDeploy,
            plugins: babelPlugins
        }),
        replace(replaceOptions),
        uglify({
            compress: {
                // compress options
                booleans: true,
                dead_code: true,
                drop_debugger: true,
                unused: true
            },
            ie8: false,
            parse: {
                // parse options
                html5_comments: false,
                shebang: false
            },
            sourceMap: isDeploy,
            toplevel: true,
            warnings: false
        }, uglifyEs.minify)
    ],
    sourcemap: isDeploy,
    output: {
        format: 'iife',
        file: path.join('build/js', 'bundle.js'),
        sourcemap: isDeploy
    }
};
```

process is started using basic rollup cli command `rollup -c rollup.config.js`

In the last 15 TC builds 5 has failed to this memory error. We are also generating sourceMaps when this error occurs.
We have 1 202 files each of them containing ES6 exported modules

```
[14:01:16][Step 6/10] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[14:01:17][Step 6/10] 
[14:01:17][Step 6/10] npm ERR! Windows_NT 6.3.9600
[14:01:17][Step 6/10] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rollup"
[14:01:17][Step 6/10] npm ERR! node v6.11.3
[14:01:17][Step 6/10] npm ERR! npm  v3.10.10
[14:01:17][Step 6/10] npm ERR! code ELIFECYCLE
[14:01:17][Step 6/10] npm ERR! SeveraUI@1.0.0 rollup: `rollup -c rollup.config.js`
[14:01:17][Step 6/10] npm ERR! Exit status 3
```

**Comment by lukastaegert** [comment]
Hi @Havunen,
did you try the solution from #1307? Did it help? As your issue is not "watch" related I suspect that this is not a memory leak and beyond making the algorithm more efficient there is not much more we can do on rollup's side.

**Comment by halfnibble** [comment]
I'm having this problem, but I'm using gulp-better-rollup for its speed, and I'm not sure how to implement @ahelmberger's solution. My only configuration options are inputOptions and outputOptions. Unless there is something I can do with gulp pipes? (Still new to pipes).

**Comment by halfnibble** [comment]
Ironically, I fixed the symptoms of this issue for my gulp build script using a plain JS object. The original implementation of `gulp-better-rollup` used a `Map()` object. By simply replacing that with a plain `{}` object, I was able to make rollup cache stable again (i.e. no out of memory errors).
https://github.com/halfnibble/gulp-better-rollup/commit/f687dd31831fa736448bd9f4cdfbf884a7c9cd14
