### ISSUE TITLE
Unused code included in output.

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#977]
Extracted from @bclinkinbeard’s [comment on #970](https://github.com/rollup/rollup/issues/970#issuecomment-249299835). Here’s a [minimal test case](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKGZvbygpKSUzQiUyMCUyRiUyRiUyMGZvbyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwZGVhZCUyMGZyb20lMjAlNUMlMjIuJTJGZGVhZCU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uKCklMjAlN0IlMjByZXR1cm4lMjAlNUMlMjJmb28lNUMlMjIlM0IlMjAlN0QlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBmb29kZWFkKCklMjAlN0IlMjByZXR1cm4lMjBkZWFkKCklM0IlMjAlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVhZC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24oKSUyMCU3QiUyMHJldHVybiUyMCU1QyUyMmRlYWQlNUMlMjIlM0IlMjAlN0QlMjIlN0QlNUQlN0Q=).

main.js:

``` js
import foo from "./foo";

console.log(foo()); // foo
```

foo.js:

``` js
import dead from "./dead";

export default function() { return "foo"; }
export function foodead() { return dead(); }
```

dead.js:

``` js
export default function() { return "dead"; }
```

The **expected output** is:

``` js
'use strict';

var foo = function() { return "foo"; }

console.log(foo()); // foo
```

The **actual output** is:

``` js
'use strict';

var dead = function() { return "dead"; }

var foo = function() { return "foo"; }

console.log(foo()); // foo
```

So, the invocation of `dead()` in foodead.js, even though the default export of dead.js is unused, is causing the definition of dead.js’s default export to be included in the output.

**Comment by bclinkinbeard** [comment]
I created a small real world example using `d3-array` as well. https://github.com/bclinkinbeard/rollup-issue-repro

**Comment by mbostock** [comment]
I discovered I can reduce the test case slightly.

main.js:

```js
import foo from "./foo";

console.log(foo()); // foo
```

foo.js:

```js
import dead from "./dead";

export default function() { return "foo"; }

export function foodead() { return "foo" + dead(); }
```

dead.js:

```js
export default function() { return "dead"; }
```

**Comment by mbostock** [comment]
I did a little digging.

In phase 3, Rollup runs each statement to see what needs to be included. For a top-level function such as foodead, that means the function’s BlockStatement is run ([Bundle.js:152](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L152)). By running `{ return 'foo' + dead(); }`, that activates the `dead` code.

I could be wrong, but I think you only want to run the block statement of a top-level functions that is called (activated?) by some other active code. But that means you can’t just do a linaer scan of the module statements, since typically a function is declared before it is called.

**Comment by mbostock** [comment]
Interestingly, this seems to be specific to default exports. It’s sort of like the opposite problem to #967? If you change it named exports ([alternate test case](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCZm9vJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKGZvbygpKSUzQiUyMCUyRiUyRiUyMGZvbyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCZGVhZCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGZGVhZCU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBmb28oKSUyMCU3QiUyMHJldHVybiUyMCU1QyUyMmZvbyU1QyUyMiUzQiUyMCU3RCU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGZvb2RlYWQoKSUyMCU3QiUyMHJldHVybiUyMCU1QyUyMmZvbyU1QyUyMiUyMCUyQiUyMGRlYWQoKSUzQiUyMCU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZWFkLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZGVhZCgpJTIwJTdCJTIwcmV0dXJuJTIwJTVDJTIyZGVhZCU1QyUyMiUzQiUyMCU3RCUyMiU3RCU1RCU3RA==)), the dead code is successfully ignored.

**Comment by kzc** [comment]
If the rollup output:
```
'use strict';

var dead = function() { return "dead"; }

var foo = function() { return "foo"; }

console.log(foo()); // foo
```
is run through rollup again it produces:
```
var foo = function() { return "foo"; }

console.log(foo()); // foo
```
Ignoring the removal of `"use strict"`, we see that it successfully removes the dead code in question.

Maybe introducing a `passes` option to rollup might be generally useful to catch situations like this. If rollup is similar to buble where magic-string is used instead of changing the AST, then pass would likely require a complete acorn reparse of the output of the last pass.

**Comment by abe33** [comment]
I'm not so sure it's related to default exports. I have tried using rollup in a test project and got the same issue of unused code preserved in the output (see the project [here](https://github.com/abe33/rollup-test)). In my case there's no default exports in any of the imported dependencies. The main file only import one function that is free of any other dependencies (https://github.com/abe33/rollup-test/blob/master/src/index.es6) and the output is filled with unused code (https://github.com/abe33/rollup-test/blob/master/lib/index.js).

What's even weirder here, is that a class is included (https://github.com/abe33/rollup-test/blob/master/lib/index.js#L22-L34) while the code that requires it isn't (https://github.com/abe33/widjet-utils/blob/master/src/index.es6#L181-L216)

**Comment by mbostock** [comment]
Thanks, @abe33. I think I’ve been able to reduce the test case even farther with your example. Here’s [the reduced test case](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCZm9vJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lNUMlMjIlM0IlNUNuJTVDbmZvbygpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGZvbygpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMmZvbyU1QyUyMiklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGJhcigpJTIwJTdCJTVDbiUyMCUyMGJheigpJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBiYXooKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJiYXolNUMlMjIpJTNCJTVDbiU3RCUyMiU3RCU1RCU3RA==), with no default exports.

main.js:

```js
import {foo} from "./foo";

foo();
```

foo.js:

```js
export function foo() {
  console.log("foo");
}

function bar() {
  baz();
}

function baz() {
  console.log("baz");
}
```

The output, including the unused `baz`:

```js
'use strict';

function foo() {
  console.log("foo");
}

function baz() {
  console.log("baz");
}

foo();
```

So like the original test case, because `bar` calls `baz`, the `baz` function declaration is included in the output, even though the code that called it (`bar`) is not.

**Comment by mbostock** [comment]
Actually, derp, this is even simpler! A [one-file test case](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBiYXIoKSUyMCU3QiU1Q24lMjAlMjBiYXooKSUzQiU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwYmF6KCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYmF6JTVDJTIyKSUzQiU1Q24lN0QlMjIlN0QlNUQlN0Q=).

main.js:

```js
function bar() {
  baz();
}

function baz() {
  console.log("baz");
}
```

The output:

```js
'use strict';

function baz() {
  console.log("baz");
}
```

**Comment by mbostock** [comment]
I’ve added this new failing test case to #978.

**Comment by Turbo87** [comment]
@Rich-Harris friendly reminder :)

**Comment by Turbo87** [comment]
seems this got resolved in #967 but the issue just wasn't closed yet. thanks!

**Comment by bclinkinbeard** [comment]
This is not fixed yet. I've updated https://github.com/bclinkinbeard/rollup-issue-repro to 0.36.3 and unused code is still being included in the output. I've checked in `bundle.js` so you can see what it's doing, whereas it should only contain the single method `min`.

**Comment by mbostock** [comment]
Here’s a versionless link of the test case, which still fails in 0.36.3: http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBiYXIoKSUyMCU3QiU1Q24lMjAlMjBiYXooKSUzQiU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwYmF6KCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYmF6JTVDJTIyKSUzQiU1Q24lN0QlMjIlN0QlNUQlN0Q=

**Comment by scola84** [comment]
In 0.34.13 my code is bundled as expected, in 0.35.0 it isn't anymore:

http://rollupjs.org/?version=0.34.13&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGdGVzdCclM0IlNUNuY29uc29sZS5sb2coc2VydmVyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGNsaWVudCUyMCU3RCUyMGZyb20lMjAnLiUyRmNsaWVudCclM0IlNUNuZXhwb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2VydmVyJyUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xpZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGdmFsdWUnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNsaWVudCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHZhbHVlKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZhbHVlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdmFsdWUlMjAlM0QlMjA0MiUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc2VydmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2VydmVyJTIwJTNEJTIwJTdCJTVDbiU1Q3R2YWx1ZSUzQSUyMCdzZXJ2ZXInJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQlN0Q=

http://rollupjs.org/?version=0.35.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGdGVzdCclM0IlNUNuY29uc29sZS5sb2coc2VydmVyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGNsaWVudCUyMCU3RCUyMGZyb20lMjAnLiUyRmNsaWVudCclM0IlNUNuZXhwb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2VydmVyJyUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xpZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGdmFsdWUnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNsaWVudCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHZhbHVlKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZhbHVlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdmFsdWUlMjAlM0QlMjA0MiUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc2VydmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2VydmVyJTIwJTNEJTIwJTdCJTVDbiU1Q3R2YWx1ZSUzQSUyMCdzZXJ2ZXInJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQlN0Q=

**Comment by bclinkinbeard** [comment]
There was a comment added (since deleted??) that pointed out the behavior changed between v0.34.13 and v0.35.0, so the culprit is somewhere in this list of commits. https://github.com/rollup/rollup/compare/v0.34.13...v0.35.0

Only a handful of those commits appear to be functional rather than CI, tests, etc. https://github.com/rollup/rollup/commit/34a13a74d0ff9414c27a55358090a580f6537ac9 seems like it may be a good candidate.

I was going to run a `git bisect` to find the exact commit but I couldn't get Rollup to build in the previous states.

**Comment by scola84** [comment]
That was me, sorry for deleting. Problem is that I could not reproduce the behavior of a simple test case in my development environment.

The test cases:

[0.34.13](http://rollupjs.org/?version=0.34.13&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGdGVzdCclM0IlNUNuY29uc29sZS5sb2coc2VydmVyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGNsaWVudCUyMCU3RCUyMGZyb20lMjAnLiUyRmNsaWVudCclM0IlNUNuZXhwb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2VydmVyJyUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xpZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGdmFsdWUnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNsaWVudCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHZhbHVlKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZhbHVlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdmFsdWUlMjAlM0QlMjA0MiUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc2VydmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2VydmVyJTIwJTNEJTIwJTdCJTVDbiU1Q3R2YWx1ZSUzQSUyMCdzZXJ2ZXInJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQlN0Q=)

[0.35.0](http://rollupjs.org/?version=0.35.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGdGVzdCclM0IlNUNuY29uc29sZS5sb2coc2VydmVyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGNsaWVudCUyMCU3RCUyMGZyb20lMjAnLiUyRmNsaWVudCclM0IlNUNuZXhwb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2VydmVyJyUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xpZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGdmFsdWUnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNsaWVudCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHZhbHVlKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZhbHVlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdmFsdWUlMjAlM0QlMjA0MiUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc2VydmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2VydmVyJTIwJTNEJTIwJTdCJTVDbiU1Q3R2YWx1ZSUzQSUyMCdzZXJ2ZXInJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQlN0Q=)

My development environment has obviously much more complicated imports. I found out that problems disappeared when I removed 'side effect' imports, like `import 'd3-selection-multi'` or `import 'moment-timezone'`. Sadly I could not reproduce that behavior in a simple test case...

**Comment by scola84** [comment]
Additionally, if you add code that is not exported, it gets added to the bundle in both versions I mentioned above.

[test case in 0.34.13](http://rollupjs.org/?version=0.34.13&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGdGVzdCclM0IlNUNuY29uc29sZS5sb2coc2VydmVyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGNsaWVudCUyMCU3RCUyMGZyb20lMjAnLiUyRmNsaWVudCclM0IlNUNuZXhwb3J0JTIwJTdCJTIwc2VydmVyJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2VydmVyJyUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xpZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGdmFsdWUnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGNsaWVudCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKHZhbHVlKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZhbHVlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwdmFsdWUlMjAlM0QlMjA0MiUzQiU1Q25jb25zb2xlLmxvZygndmFsdWUnKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyc2VydmVyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2VydmVyJTIwJTNEJTIwJTdCJTVDbiU1Q3R2YWx1ZSUzQSUyMCdzZXJ2ZXInJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQlN0Q=)

I would not expect `console.log('value')` from `value.js` to appear in the bundle...

**Comment by mbostock** [comment]
0.35.0 was a complete rewrite of the tree-shaking code (see #902).

**Comment by zbraniecki** [comment]
Is there any plan to fix this regression?

**Comment by thisconnect** [comment]
@mbostock shouldn't there be at least one export or one import? your example is just 2 functions that are never called.

**Comment by mbostock** [comment]
@thisconnect That is the definition of “unused code”. It’s perfectly valid to have an entry module that has no imports or exports; Rollup should then retain only code with side-effects.

**Comment by aendrew** [comment]
Does #1106 actually fix this? If so, any idea when it'll get merged? This issue's now been open for two months and it's effectively caused me to switch from Rollup to Webpack for one of my writing projects... 😞

**Comment by Rich-Harris** [comment]
Sorry for the delay everyone! #1106 is merged, I've just released 0.36.4 with the fix

**Comment by bclinkinbeard** [comment]
Thanks for the improvement! Sorry to be "that person" but there are still some cases where unused code is getting through.

[This example](http://rollupjs.org/?version=0.36.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwYmF6JTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZsaWIlNUMlMjIlM0IlNUNuJTVDbmJheigpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBmb28lN0QlMjBmcm9tJTIwJy4lMkZmb28nJTNCJTVDbmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMGJhciU3RCUyMGZyb20lMjAnLiUyRmJhciclM0IlNUNuZXhwb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwYmF6JTdEJTIwZnJvbSUyMCcuJTJGYmF6JyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyZm9vJTVDJTIyKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvbyclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMCh1bW0pJTIwJTdCJTVDbiUyMCUyMGlmJTIwKHVtbSklMjB1bW0lMjAlM0QlMjBobW0oKSUzQiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJiYXIlNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBobW0lMjAoKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjB0cnVlJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXouanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYmF6JTVDJTIyKSUzQiU1Q24lN0QlMjIlN0QlNUQlN0Q=) shows that a function that is called as a result of a conditional is still being included, even though the function that houses the conditional is never called and is not included itself. If you remove the `if` from line 4 of `bar.js` so it's simply `hmm();`, that function is no longer included in the output.

**Comment by kzc** [comment]
@bclinkinbeard I opened a new ticket for your test case.
